name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: Build
      run: |
        npm install
        npm run build
    - name: Deploy
      run: |
        git config user.name dong
        git config user.email 2710732812@qq.com
        git add .
        git commit -m "deploy"
        git push --force origin main
    - name: Publish
      run: |
        npm publish
